# Generated by Django 4.2.1 on 2023-06-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('bot_name', models.CharField(default='trade_bot', max_length=255)),
                ('token', models.IntegerField()),
                ('balance', models.FloatField()),
                ('base_balance', models.FloatField()),
                ('amount_BNBBUSD', models.IntegerField(default=0)),
                ('amount_BTCBUSD', models.IntegerField(default=0)),
                ('amount_ETHBUSD', models.IntegerField(default=0)),
                ('amount_LTCBUSD', models.IntegerField(default=0)),
                ('amount_TRXBUSD', models.IntegerField(default=0)),
                ('amount_XRPBUSD', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('amount', models.IntegerField()),
                ('token_id', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
        ),
    ]
