# Generated by Django 4.1.6 on 2023-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_BNBBUSD",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_BTCBUSD",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_ETHBUSD",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_LTCBUSD",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_TRXBUSD",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_XRPBUSD",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bot",
            name="token",
            field=models.CharField(default="key", max_length=255),
        ),
    ]
