# Generated by Django 4.1.6 on 2023-06-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_bot_is_public_transaction_amount_bnbbusd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
